<div class='container'>
    <% if @catch.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@catch.errors.count, "error") %>が原因でこの記事を保存できませんでした</h2>
        <ul>
          <% @catch.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Catch</h1>
  		<%= render 'form', catch: @catch %>
  		<%= link_to 'Show', @catch %> |
  		<%= link_to 'Back', catches_path, class: "back" %>
  </div>
</div>